// Generates, from catalog.mjs + pages.mjs:
//   supabase/seed.sql          — demo data for a fresh database (supabase db reset)
//   src/lib/demo/dataset.json  — the same rows for demo mode (no Supabase project)
//
//   npm run seed:generate

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import {
  categories, collections, products, describe, shippingMethods, coupons,
  demoUsers, reviews, verifiedPurchases,
} from "./catalog.mjs";
import { pages } from "./pages.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

const uuid = (key) => {
  const h = createHash("sha1").update(`auraq:${key}`).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const hashInt = (key) => parseInt(createHash("md5").update(key).digest("hex").slice(0, 8), 16);
const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a) => (a ? `array[${a.map(q).join(", ")}]` : "null");
const json = (v) => `${q(JSON.stringify(v))}::jsonb`;

const out = [];
const emit = (s) => out.push(s);

// Rows mirrored into the demo-mode dataset. Timestamps are stored as
// "days ago" so the demo stays fresh whenever it runs.
const PAGES_UPDATED_AT = "2026-09-15T10:00:00+05:00";
const dataset = {
  categories: [], collections: [], products: [], product_images: [], product_variants: [],
  product_collections: [], shipping_methods: [], coupons: [], pages: [], reviews: [], orders: [],
};

emit(`-- ============================================================================
-- DEMO SEED DATA — generated by scripts/seed/generate-seed.mjs. Do not edit.
-- Catalogue, policies, shipping, coupons, and demo customers/orders/reviews.
-- Remove the demo customers section before going live with real customers.
-- ============================================================================
begin;
`);

// Categories (parents first)
emit("-- Categories");
for (const c of [...categories].sort((a, b) => Number(Boolean(a.parent)) - Number(Boolean(b.parent)))) {
  emit(`insert into public.categories (id, parent_id, name, slug, description, image_url, position) values (${q(uuid(`cat:${c.slug}`))}, ${c.parent ? q(uuid(`cat:${c.parent}`)) : "null"}, ${q(c.name)}, ${q(c.slug)}, ${q(c.description)}, ${q(c.image)}, ${c.position});`);
  dataset.categories.push({ id: uuid(`cat:${c.slug}`), parent_id: c.parent ? uuid(`cat:${c.parent}`) : null, name: c.name, slug: c.slug, description: c.description, image_url: c.image, position: c.position });
}

emit("\n-- Collections");
for (const c of collections) {
  emit(`insert into public.collections (id, name, slug, description, image_url, position) values (${q(uuid(`col:${c.slug}`))}, ${q(c.name)}, ${q(c.slug)}, ${q(c.description)}, ${q(c.image)}, ${c.position});`);
  dataset.collections.push({ id: uuid(`col:${c.slug}`), name: c.name, slug: c.slug, description: c.description, image_url: c.image, position: c.position });
}

emit("\n-- Products");
const catCode = (slug) => slug.replace(/[^a-z0-9]/g, "").slice(0, 3).toUpperCase();
products.forEach((p, i) => {
  const d = describe(p);
  const sku = `AQ-${catCode(p.category)}-${String(101 + i)}`;
  p.sku = sku;
  p.id = uuid(`prod:${p.slug}`);
  emit(`insert into public.products (id, category_id, name, slug, short_description, description, price, compare_at_price, sku, stock_quantity, status, featured, material, care_instructions, details, sales_count, created_at) values (${q(p.id)}, ${q(uuid(`cat:${p.category}`))}, ${q(p.name)}, ${q(p.slug)}, ${q(d.short)}, ${q(d.description)}, ${p.price}, ${p.compare ?? "null"}, ${q(sku)}, 0, 'active', ${p.featured ? "true" : "false"}, ${q(d.material)}, ${q(d.care)}, ${json(d.details)}, ${p.sales ?? 0}, now() - interval '${i * 2 + 1} days');`);
  dataset.products.push({ id: p.id, category_id: uuid(`cat:${p.category}`), name: p.name, slug: p.slug, short_description: d.short, description: d.description, price: p.price, compare_at_price: p.compare ?? null, sku, featured: Boolean(p.featured), material: d.material, care_instructions: d.care, details: d.details, sales_count: p.sales ?? 0, created_days_ago: i * 2 + 1, rating_avg: 0, rating_count: 0 });

  const colour = p.colors[0][0];
  emit(`insert into public.product_images (product_id, url, alt_text, position) values (${q(p.id)}, ${q(`/images/products/${p.slug}-1.jpg`)}, ${q(`${p.name} — ${p.piece} in ${colour}`)}, 0), (${q(p.id)}, ${q(`/images/products/${p.slug}-2.jpg`)}, ${q(`${p.name} — ${p.unstitched ? "fabric" : "embroidery"} detail`)}, 1);`);
  dataset.product_images.push(
    { product_id: p.id, url: `/images/products/${p.slug}-1.jpg`, alt_text: `${p.name} — ${p.piece} in ${colour}`, position: 0 },
    { product_id: p.id, url: `/images/products/${p.slug}-2.jpg`, alt_text: `${p.name} — ${p.unstitched ? "fabric" : "embroidery"} detail`, position: 1 },
  );

  let pos = 0;
  for (const [color, hex] of p.colors) {
    const colourCode = color.split(" ").map((w) => w[0]).join("").toUpperCase();
    for (const size of p.sizes) {
      const key = `${p.slug}:${color}:${size}`;
      const h = hashInt(key);
      let stock = p.soldOut ? 0 : (h % 14) + 1;
      if (!p.soldOut && h % 9 === 0) stock = 0; // occasional sold-out size
      if (!p.soldOut && h % 7 === 0) stock = 2; // low stock signal
      const vSku = `${sku}-${colourCode}-${size === "One Size" ? "OS" : size}`;
      emit(`insert into public.product_variants (id, product_id, name, sku, size, color, color_hex, stock_quantity, position) values (${q(uuid(`var:${key}`))}, ${q(p.id)}, ${q(`${color} / ${size}`)}, ${q(vSku)}, ${q(size)}, ${q(color)}, ${q(hex)}, ${stock}, ${pos});`);
      dataset.product_variants.push({ id: uuid(`var:${key}`), product_id: p.id, name: `${color} / ${size}`, sku: vSku, size, color, color_hex: hex, price: null, stock_quantity: stock, position: pos });
      pos++;
    }
  }
  p.collections.forEach((c, j) => {
    emit(`insert into public.product_collections (product_id, collection_id, position) values (${q(p.id)}, ${q(uuid(`col:${c}`))}, ${i * 10 + j});`);
    dataset.product_collections.push({ product_id: p.id, collection_id: uuid(`col:${c}`), position: i * 10 + j });
  });
});

emit("\n-- Shipping methods");
for (const m of shippingMethods) {
  emit(`insert into public.shipping_methods (code, name, description, price, free_shipping_threshold, min_days, max_days, countries, position) values (${q(m.code)}, ${q(m.name)}, ${q(m.description)}, ${m.price}, ${m.free ?? "null"}, ${m.min}, ${m.max}, ${arr(m.countries)}, ${m.position});`);
  dataset.shipping_methods.push({ code: m.code, name: m.name, description: m.description, price: m.price, free_shipping_threshold: m.free ?? null, min_days: m.min, max_days: m.max, countries: m.countries ?? null, position: m.position });
}

emit("\n-- Coupons");
for (const c of coupons) {
  emit(`insert into public.coupons (code, description, type, value, minimum_order, maximum_discount, usage_limit_per_customer, expires_at) values (${q(c.code)}, ${q(c.description)}, ${q(c.type)}, ${c.value}, ${c.min}, ${c.max ?? "null"}, ${c.perCustomer ?? "null"}, ${q(c.expires ?? null)});`);
  dataset.coupons.push({ code: c.code, description: c.description, type: c.type, value: c.value, minimum_order: c.min, maximum_discount: c.max ?? null, usage_limit_per_customer: c.perCustomer ?? null, starts_at: null, expires_at: c.expires ?? null });
}

emit("\n-- Pages (editable policies)");
for (const pg of pages) {
  emit(`insert into public.pages (slug, title, summary, content) values (${q(pg.slug)}, ${q(pg.title)}, ${q(pg.summary)}, ${q(pg.content.trim())});`);
  dataset.pages.push({ slug: pg.slug, title: pg.title, summary: pg.summary ?? null, content: pg.content.trim(), updated_at: PAGES_UPDATED_AT });
}

emit(`
-- ---------------------------------------------------------------------------
-- DEMO customers, delivered orders and reviews (remove before launch)
-- ---------------------------------------------------------------------------`);
demoUsers.forEach((u, i) => {
  u.id = uuid(`user:${u.email}`);
  emit(`insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_user_meta_data, created_at, updated_at) values (${q(u.id)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${q(u.email)}, '', now(), ${json({ first_name: u.first, last_name: u.last })}, now() - interval '${120 - i * 7} days', now());`);
});

const bySlug = Object.fromEntries(products.map((p) => [p.slug, p]));
let orderSeq = 100001;
for (const [userIndex, slugs] of verifiedPurchases()) {
  const u = demoUsers[userIndex];
  const orderId = uuid(`order:${u.email}`);
  const items = [...slugs].map((s) => bySlug[s]);
  const subtotal = items.reduce((sum, p) => sum + p.price, 0);
  const shipping = subtotal >= 5000 ? 0 : 250;
  const address = { first_name: u.first, last_name: u.last, phone: "+92 300 0000000", address_line_1: "House 1, Street 1", city: u.city, province: null, postal_code: null, country: "PK" };
  emit(`insert into public.orders (id, user_id, email, phone, status, payment_status, payment_method, shipping_method, shipping_method_name, subtotal, discount, shipping_cost, tax, total, shipping_address, billing_address, created_at) values (${q(orderId)}, ${q(u.id)}, ${q(u.email)}, '+92 300 0000000', 'delivered', 'paid', 'cod', 'standard', 'Standard Delivery', ${subtotal}, 0, ${shipping}, 0, ${subtotal + shipping}, ${json(address)}, ${json(address)}, now() - interval '${40 + userIndex} days');`);
  const daysAgo = 40 + userIndex;
  const order = {
    id: orderId, order_number: `AQ-${orderSeq++}`, access_token: uuid(`order-token:${u.email}`), user_id: u.id,
    email: u.email, phone: "+92 300 0000000", status: "delivered", payment_status: "paid", payment_method: "cod",
    shipping_method: "standard", shipping_method_name: "Standard Delivery", subtotal, discount: 0, shipping_cost: shipping,
    tax: 0, total: subtotal + shipping, coupon_code: null, shipping_address: address, billing_address: address, notes: null,
    created_days_ago: daysAgo, items: [],
    history: [
      { status: "confirmed", note: null, created_days_ago: daysAgo },
      { status: "processing", note: null, created_days_ago: daysAgo - 1 },
      { status: "shipped", note: "Handed to courier", created_days_ago: daysAgo - 2 },
      { status: "delivered", note: null, created_days_ago: daysAgo - 4 },
    ],
  };
  for (const p of items) {
    const color = p.colors[0][0];
    const size = p.sizes.includes("M") ? "M" : p.sizes[0];
    emit(`insert into public.order_items (order_id, product_id, variant_id, product_name, product_slug, image_url, sku, variant_name, size, color, price, quantity) values (${q(orderId)}, ${q(p.id)}, ${q(uuid(`var:${p.slug}:${color}:${size}`))}, ${q(p.name)}, ${q(p.slug)}, ${q(`/images/products/${p.slug}-1.jpg`)}, ${q(p.sku)}, ${q(`${color} / ${size}`)}, ${q(size)}, ${q(color)}, ${p.price}, 1);`);
    order.items.push({ id: uuid(`order-item:${u.email}:${p.slug}`), product_id: p.id, variant_id: uuid(`var:${p.slug}:${color}:${size}`), product_name: p.name, product_slug: p.slug, image_url: `/images/products/${p.slug}-1.jpg`, sku: p.sku, variant_name: `${color} / ${size}`, size, color, price: p.price, quantity: 1 });
  }
  dataset.orders.push(order);
}

reviews.forEach(([userIndex, slug, rating, title, content, verified], i) => {
  const u = demoUsers[userIndex];
  emit(`insert into public.reviews (product_id, user_id, rating, title, content, status, created_at) values (${q(bySlug[slug].id)}, ${q(u.id)}, ${rating}, ${q(title)}, ${q(content)}, 'approved', now() - interval '${30 - (i % 25)} days');`);
  dataset.reviews.push({ id: uuid(`review:${u.email}:${slug}`), product_id: bySlug[slug].id, user_id: u.id, author_name: `${u.first} ${u.last[0]}.`, rating, title, content, verified_purchase: Boolean(verified), status: "approved", created_days_ago: 30 - (i % 25) });
});

// Mirror the rating aggregate the database maintains with a trigger.
for (const p of dataset.products) {
  const ratings = dataset.reviews.filter((r) => r.product_id === p.id).map((r) => r.rating);
  p.rating_count = ratings.length;
  p.rating_avg = ratings.length ? Math.round((ratings.reduce((a, b) => a + b, 0) / ratings.length) * 100) / 100 : 0;
}

emit("\ncommit;\n");

writeFileSync(path.join(root, "supabase/seed.sql"), out.join("\n"));
writeFileSync(path.join(root, "src/lib/demo/dataset.json"), JSON.stringify(dataset) + "\n");
console.log(`Wrote supabase/seed.sql and src/lib/demo/dataset.json (${products.length} products, ${reviews.length} reviews)`);
