// Generates supabase/seed.sql from catalog.mjs + pages.mjs.
//   node scripts/seed/generate-seed.mjs
// The output is idempotent-friendly for a fresh database (supabase db reset).

import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import {
  categories, collections, products, describe, shippingMethods, coupons,
  demoUsers, reviews, verifiedPurchases,
} from "./catalog.mjs";
import { pages } from "./pages.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

const uuid = (key) => {
  const h = createHash("sha1").update(`auraq:${key}`).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const hashInt = (key) => parseInt(createHash("md5").update(key).digest("hex").slice(0, 8), 16);
const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a) => (a ? `array[${a.map(q).join(", ")}]` : "null");
const json = (v) => `${q(JSON.stringify(v))}::jsonb`;

const out = [];
const emit = (s) => out.push(s);

emit(`-- ============================================================================
-- DEMO SEED DATA — generated by scripts/seed/generate-seed.mjs. Do not edit.
-- Catalogue, policies, shipping, coupons, and demo customers/orders/reviews.
-- Remove the demo customers section before going live with real customers.
-- ============================================================================
begin;
`);

// Categories (parents first)
emit("-- Categories");
for (const c of [...categories].sort((a, b) => Number(Boolean(a.parent)) - Number(Boolean(b.parent)))) {
  emit(`insert into public.categories (id, parent_id, name, slug, description, image_url, position) values (${q(uuid(`cat:${c.slug}`))}, ${c.parent ? q(uuid(`cat:${c.parent}`)) : "null"}, ${q(c.name)}, ${q(c.slug)}, ${q(c.description)}, ${q(c.image)}, ${c.position});`);
}

emit("\n-- Collections");
for (const c of collections) {
  emit(`insert into public.collections (id, name, slug, description, image_url, position) values (${q(uuid(`col:${c.slug}`))}, ${q(c.name)}, ${q(c.slug)}, ${q(c.description)}, ${q(c.image)}, ${c.position});`);
}

emit("\n-- Products");
const catCode = (slug) => slug.replace(/[^a-z0-9]/g, "").slice(0, 3).toUpperCase();
products.forEach((p, i) => {
  const d = describe(p);
  const sku = `AQ-${catCode(p.category)}-${String(101 + i)}`;
  p.sku = sku;
  p.id = uuid(`prod:${p.slug}`);
  emit(`insert into public.products (id, category_id, name, slug, short_description, description, price, compare_at_price, sku, stock_quantity, status, featured, material, care_instructions, details, sales_count, created_at) values (${q(p.id)}, ${q(uuid(`cat:${p.category}`))}, ${q(p.name)}, ${q(p.slug)}, ${q(d.short)}, ${q(d.description)}, ${p.price}, ${p.compare ?? "null"}, ${q(sku)}, 0, 'active', ${p.featured ? "true" : "false"}, ${q(d.material)}, ${q(d.care)}, ${json(d.details)}, ${p.sales ?? 0}, now() - interval '${i * 2 + 1} days');`);

  const colour = p.colors[0][0];
  emit(`insert into public.product_images (product_id, url, alt_text, position) values (${q(p.id)}, ${q(`/images/products/${p.slug}-1.jpg`)}, ${q(`${p.name} — ${p.piece} in ${colour}`)}, 0), (${q(p.id)}, ${q(`/images/products/${p.slug}-2.jpg`)}, ${q(`${p.name} — ${p.unstitched ? "fabric" : "embroidery"} detail`)}, 1);`);

  let pos = 0;
  for (const [color, hex] of p.colors) {
    const colourCode = color.split(" ").map((w) => w[0]).join("").toUpperCase();
    for (const size of p.sizes) {
      const key = `${p.slug}:${color}:${size}`;
      const h = hashInt(key);
      let stock = p.soldOut ? 0 : (h % 14) + 1;
      if (!p.soldOut && h % 9 === 0) stock = 0; // occasional sold-out size
      if (!p.soldOut && h % 7 === 0) stock = 2; // low stock signal
      const vSku = `${sku}-${colourCode}-${size === "One Size" ? "OS" : size}`;
      emit(`insert into public.product_variants (id, product_id, name, sku, size, color, color_hex, stock_quantity, position) values (${q(uuid(`var:${key}`))}, ${q(p.id)}, ${q(`${color} / ${size}`)}, ${q(vSku)}, ${q(size)}, ${q(color)}, ${q(hex)}, ${stock}, ${pos++});`);
    }
  }
  p.collections.forEach((c, j) => {
    emit(`insert into public.product_collections (product_id, collection_id, position) values (${q(p.id)}, ${q(uuid(`col:${c}`))}, ${i * 10 + j});`);
  });
});

emit("\n-- Shipping methods");
for (const m of shippingMethods) {
  emit(`insert into public.shipping_methods (code, name, description, price, free_shipping_threshold, min_days, max_days, countries, position) values (${q(m.code)}, ${q(m.name)}, ${q(m.description)}, ${m.price}, ${m.free ?? "null"}, ${m.min}, ${m.max}, ${arr(m.countries)}, ${m.position});`);
}

emit("\n-- Coupons");
for (const c of coupons) {
  emit(`insert into public.coupons (code, description, type, value, minimum_order, maximum_discount, usage_limit_per_customer, expires_at) values (${q(c.code)}, ${q(c.description)}, ${q(c.type)}, ${c.value}, ${c.min}, ${c.max ?? "null"}, ${c.perCustomer ?? "null"}, ${q(c.expires ?? null)});`);
}

emit("\n-- Pages (editable policies)");
for (const pg of pages) {
  emit(`insert into public.pages (slug, title, summary, content) values (${q(pg.slug)}, ${q(pg.title)}, ${q(pg.summary)}, ${q(pg.content.trim())});`);
}

emit(`
-- ---------------------------------------------------------------------------
-- DEMO customers, delivered orders and reviews (remove before launch)
-- ---------------------------------------------------------------------------`);
demoUsers.forEach((u, i) => {
  u.id = uuid(`user:${u.email}`);
  emit(`insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_user_meta_data, created_at, updated_at) values (${q(u.id)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${q(u.email)}, '', now(), ${json({ first_name: u.first, last_name: u.last })}, now() - interval '${120 - i * 7} days', now());`);
});

const bySlug = Object.fromEntries(products.map((p) => [p.slug, p]));
for (const [userIndex, slugs] of verifiedPurchases()) {
  const u = demoUsers[userIndex];
  const orderId = uuid(`order:${u.email}`);
  const items = [...slugs].map((s) => bySlug[s]);
  const subtotal = items.reduce((sum, p) => sum + p.price, 0);
  const shipping = subtotal >= 5000 ? 0 : 250;
  const address = { first_name: u.first, last_name: u.last, phone: "+92 300 0000000", address_line_1: "House 1, Street 1", city: u.city, province: null, postal_code: null, country: "PK" };
  emit(`insert into public.orders (id, user_id, email, phone, status, payment_status, payment_method, shipping_method, shipping_method_name, subtotal, discount, shipping_cost, tax, total, shipping_address, billing_address, created_at) values (${q(orderId)}, ${q(u.id)}, ${q(u.email)}, '+92 300 0000000', 'delivered', 'paid', 'cod', 'standard', 'Standard Delivery', ${subtotal}, 0, ${shipping}, 0, ${subtotal + shipping}, ${json(address)}, ${json(address)}, now() - interval '${40 + userIndex} days');`);
  for (const p of items) {
    const color = p.colors[0][0];
    const size = p.sizes.includes("M") ? "M" : p.sizes[0];
    emit(`insert into public.order_items (order_id, product_id, variant_id, product_name, product_slug, image_url, sku, variant_name, size, color, price, quantity) values (${q(orderId)}, ${q(p.id)}, ${q(uuid(`var:${p.slug}:${color}:${size}`))}, ${q(p.name)}, ${q(p.slug)}, ${q(`/images/products/${p.slug}-1.jpg`)}, ${q(p.sku)}, ${q(`${color} / ${size}`)}, ${q(size)}, ${q(color)}, ${p.price}, 1);`);
  }
}

reviews.forEach(([userIndex, slug, rating, title, content], i) => {
  const u = demoUsers[userIndex];
  emit(`insert into public.reviews (product_id, user_id, rating, title, content, status, created_at) values (${q(bySlug[slug].id)}, ${q(u.id)}, ${rating}, ${q(title)}, ${q(content)}, 'approved', now() - interval '${30 - (i % 25)} days');`);
});

emit("\ncommit;\n");

writeFileSync(path.join(root, "supabase/seed.sql"), out.join("\n"));
console.log(`Wrote supabase/seed.sql (${products.length} products, ${reviews.length} reviews)`);
